onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_dev_rdata_i
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_csi_rx_clk
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_frame_vsync
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_frame_href
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_frame_Gray
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_pixel_clk
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/lcd_vs
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/lcd_request
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/lcd_data
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_awid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_awaddr
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_awlen
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_awvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_awready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_aw_id
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_aw_addr
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_aw_len
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_aw_valid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_aw_ready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_wid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_wdata
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_wstrb
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_wlast
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_wvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_wready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_w_id
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_w_data
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_w_strb
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_w_last
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_w_valid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_w_ready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_bresp
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_bvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_bready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_arid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_araddr
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_arvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_arready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_ar_id
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_ar_addr
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_ar_len
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_ar_valid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_ar_ready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_rid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_rdata
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_rlast
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_rvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_rready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_rresp
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_r_id
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_r_data
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_r_last
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_r_valid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_r_ready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/cmos_r_resp
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_aid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_aaddr
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_alen
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_asize
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_awsize
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_arsize
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_aburst
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_alock
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_avalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_aready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_atype
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_cal_pass
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_cal_done
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/w_hbram_cal_dbg
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_awvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_awaddr
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_awlock
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_awready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_awid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_awburst
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_awsize
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_awlen
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_wvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_wlast
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_wid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_wdata
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_wstrb
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_wready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_bvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_bready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_bid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_bresp
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_arvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_araddr
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_arlock
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_arready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_arid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_arburst
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_arsize
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_arlen
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_rvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_rlast
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_rready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_rid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_rdata
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/s_axi_rresp
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/m_axi_awlock
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/m_axi_awprot
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/m_axi_bresp
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/m_axi_arlock
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/m_axi_arprot
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_clk
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_reset
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_awid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_awaddr
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_awlen
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_awsize
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_awburst
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_awlock
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_awcache
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_awprot
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_awqos
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_awvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_awready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_wdata
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_wstrb
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_wlast
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_wvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_wready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_bid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_bresp
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_bvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_bready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_arid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_araddr
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_arlen
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_arsize
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_arburst
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_arlock
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_arcache
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_arprot
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_arqos
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_arvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_arready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_rid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_rdata
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_rresp
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_rlast
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_rvalid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/axi_rready
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/wframe_pclk
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/wframe_vsync
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/wframe_data_en
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/wframe_data
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rframe_pclk
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rframe_vsync
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rframe_data_valid
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rframe_data_en
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rframe_data
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rframe_idle
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/tp_o
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rc_wframe_index
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rc_rframe_index
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_wframe_index_p1
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_wframe_index_next
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/r_wframe_index_last
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/r_wframe_inc
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/r_rframe_inc
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_wfifo_pempty
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_wfifo_empty
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_wfifo_ren
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_wfifo_rdata
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rs_w
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/ws_w_idle
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/ws_w_wdata
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/ws_w_winc
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/ws_w_eof
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/ws_w_wend
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rc_w_ptr
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rc_w_eof
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/r_w_rst
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rc_burst
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/r_wframe_sync
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/r_weof_pending
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/r_wfifo_wdata
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_wfifo_wdata
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rc_wfifo_we
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rc_r_ptr
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_rfifo_wfull
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/r_r_eof
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rs_r
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/ws_r_idle
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/ws_r_rbufchk
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/ws_r_rreq
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/ws_r_rinc
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/ws_r_wait
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/ws_r_chk
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/r_rframe_vsync
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_rfifo_rst
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_rfifo_aempty
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_rfifo_empty
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_rframe_data_en_fifo
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_rframe_data_en_load
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_rframe_data_gen
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_rframe_data_en
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/rc_rfifo_rd
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/w_rfifo_rend
add wave -noupdate /tb_example_top/u_dut/u_inter_connector/u_axi4_ctrl/r_rframe_data_gen
add wave -noupdate /tb_example_top/u_dut/led_o
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {668857168 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 472
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {8524650175 ps}
